# SEO Settings
title: Tagir Sabirov's Personal Website
description: Tagir Sabirov's Personal Website & Blog

# Rendering Settings
include:
- _pages
exclude:
- ".gitignore"
- CNAME
- README.md
- Gemfile
- Gemile.lock
- scripts
theme: jekyll-theme-cayman
plugins:
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
paginate: 12
paginate_path: "/blog/page-:num/"